### PR TITLE
Added domain classes for Lists

### PR DESCRIPTION
**Pull request by Leguan16**
This is a pull request draft to provide Lists support to the program.

Currently standard lists are used and are expected to be replaced with the new Lists.

### CODE REVIEW

**Comment by jackie35er** [comment]
Gehts dir gut?

**Comment by Leguan16** [comment]
war nach der Mathe Schularbeit lol was denkst du?

**Comment by jackie35er** [comment]
> war nach der Mathe Schularbeit lol was denkst du?

image

**Comment by Leguan16** [comment]
kootlin ist immer noch grindig

**Pull request closed without merging**
